<?php
declare(strict_types=1);
require __DIR__.'/support/Recording_database.php';
require dirname(__DIR__).'/application/bootstrap.php';
use Pk\Core\{Context,Database,Database_error,Problem};
$passed=0;$failed=0;
function check_native(string $name,callable $test): void { global $passed,$failed;try{$test();++$passed;echo "PASS $name\n";}catch(Throwable $e){++$failed;echo "FAIL $name: {$e->getMessage()}\n";} }
function expect_native(bool $value,string $message='Assertion failed'): void { if(!$value)throw new RuntimeException($message); }
function expect_error(string $class,callable $work): Throwable { try{$work();}catch(Throwable $e){if($e instanceof $class)return $e;throw $e;}throw new RuntimeException('Expected '.$class); }
function fixture_db(): array { $driver=new CI_DB_query_builder();return [new Database($driver),$driver]; }
check_native('successful unit of work commits once and returns its value',function(){[$db,$driver]=fixture_db();$v=$db->transaction(fn()=>42);expect_native($v===42&&$driver->events===['begin','commit']&&!$db->in_transaction());});
check_native('exception rolls back the outer transaction',function(){[$db,$driver]=fixture_db();expect_error(Problem::class,fn()=>$db->transaction(fn()=>throw new Problem('invalid')));expect_native($driver->events===['begin','rollback']&&!$db->in_transaction());});
check_native('nested successful work cannot commit its caller transaction',function(){[$db,$driver]=fixture_db();$db->transaction(fn()=>$db->transaction(fn()=>12));expect_native($driver->events===['begin','commit']);});
check_native('swallowed nested exception makes outer transaction rollback-only',function(){[$db,$driver]=fixture_db();expect_error(Database_error::class,fn()=>$db->transaction(function()use($db){try{$db->transaction(fn()=>throw new Problem('invalid'));}catch(Problem){}return 9;}));expect_native($driver->events===['begin','rollback']);});
check_native('failed insert throws rather than returning an apparent successful ID',function(){[$db,$driver]=fixture_db();$driver->writeResult=false;$driver->lastError=['code'=>1062,'message'=>'duplicate'];$e=expect_error(Database_error::class,fn()=>$db->transaction(fn()=>$db->insert('areas',['name'=>'duplicate'])));expect_native($e->driverCode===1062&&$e->isConflict()&&$driver->events===['begin','rollback']);});
check_native('caught database error still prevents committing other writes',function(){[$db,$driver]=fixture_db();$driver->writeResult=false;expect_error(Database_error::class,fn()=>$db->transaction(function()use($db){try{$db->insert('areas',['name'=>'duplicate']);}catch(Database_error){}return 'not success';}));expect_native(!in_array('commit',$driver->events,true));});
check_native('failed query is not confused with an empty successful result',function(){[$db,$driver]=fixture_db();$driver->lastError=['code'=>1054,'message'=>'bad column'];expect_error(Database_error::class,fn()=>$db->rows(false));expect_native($db->rows(new CI_DB_result())===[]);});
check_native('query results keep numeric IDs but preserve text numbers and nulls',function(){[$db]=fixture_db();$rows=$db->rows(new CI_DB_result([['id'=>'7','version'=>'0','number'=>'0007','huge'=>'18446744073709551615','nullable'=>null]],['id'=>'bigint','version'=>'int','number'=>'varchar','huge'=>'bigint','nullable'=>'int']));expect_native($rows===[['id'=>7,'version'=>0,'number'=>'0007','huge'=>'18446744073709551615','nullable'=>null]]);});
check_native('a lock outside a transaction is rejected before querying',function(){[$db,$driver]=fixture_db();expect_error(LogicException::class,fn()=>$db->lock('users',1));expect_native($driver->queries===[]);});
check_native('a stale locked record produces a version conflict',function(){[$db,$driver]=fixture_db();$driver->queued=[new CI_DB_result([['id'=>1,'version'=>3]])];$error=expect_error(Problem::class,fn()=>$db->transaction(fn()=>$db->lock('users',1,2)));expect_native($error->status===409&&str_ends_with($driver->queries[0][0],'FOR UPDATE'));});
check_native('audit tables cannot be updated through shared persistence',function(){[$db,$driver]=fixture_db();foreach(['audit_logs','status_history','workflow_history']as$table)expect_error(LogicException::class,fn()=>$db->update($table,1,['action'=>'tampered']));expect_native($driver->queries===[]);});
check_native('invalid model identifiers fail before any query',function(){[$db,$driver]=fixture_db();expect_error(LogicException::class,fn()=>$db->insert('users; DROP TABLE users',[]));expect_native($driver->queries===[]);});
check_native('model writes pass unmodified values into Query Builder',function(){[$db,$driver]=fixture_db();$value="O'Reilly %_000";$id=$db->insert('areas',['name'=>$value]);expect_native($id===18&&$driver->queries[0][2]['set']['name']===$value);});
check_native('role-based approvers exclude inactive accounts and requester',function(){[$db,$driver]=fixture_db();$ctx=new Context($db);$m=$ctx->model(Workflow_model::class);$m->eligible_approvers('role',3,7);$sql=$driver->queries[0][0];expect_native(str_contains($sql,'u.id != 7')&&str_contains($sql,'u.active = 1')&&str_contains($sql,'r.active = 1')&&str_contains($sql,'r.id = 3'));});
check_native('read model applies zero search text instead of dropping it',function(){[$db,$driver]=fixture_db();$ctx=new Context($db);$ctx->user=['id'=>7];$p=new ReflectionProperty(Context::class,'permissions');$p->setAccessible(true);$p->setValue($ctx,['notifications.view']);$driver->queued=[new CI_DB_result([['n'=>0]]),new CI_DB_result([['n'=>0]]),new CI_DB_result()];$ctx->model(Read_model::class)->listing('notifications',['q'=>'0']);expect_native(str_contains($driver->queries[2][0],"LIKE '%0%'"));});
check_native('task membership requires JSON_CONTAINS true, never IS NULL',function(){[$db,$driver]=fixture_db();$ctx=new Context($db);$ctx->user=['id'=>7];$p=new ReflectionProperty(Context::class,'permissions');$p->setAccessible(true);$p->setValue($ctx,['requests.view']);$driver->queued=[new CI_DB_result([['n'=>0]]),new CI_DB_result([['n'=>0]]),new CI_DB_result()];$ctx->model(Read_model::class)->listing('my_tasks',[]);$sql=$driver->queries[2][0];expect_native(str_contains($sql,'JSON_CONTAINS')&&str_contains($sql,') = 1')&&!str_contains($sql,") IS NULL"),$sql);});
check_native('models share one native driver and cache only within their context',function(){[$db,$driver]=fixture_db();$ctx=new Context($db);expect_native($ctx->model(Auth_model::class)===$ctx->model(Auth_model::class));expect_native($ctx->model(Auth_model::class)->db===$ctx->model(Document_model::class)->db);});
check_native('native MySQL conflict codes map to conflicts; unavailable DB does not',function(){foreach([1062,1205,1213,1451,1452,3819]as$code)expect_native((new Database_error('x',$code))->isConflict());expect_native(!(new Database_error('offline',2002))->isConflict());});
check_native('wrong database driver cannot become a hidden fallback',function(){$driver=new CI_DB_query_builder();$driver->dbdriver='sqlite';expect_error(LogicException::class,fn()=>new Database($driver));});
echo "$passed native database isolation checks passed; $failed failed (connection/result doubles; NOT live MySQL).\n";
exit($failed?1:0);
