<?php
return [
    'Maintenance_model' => 'models/Maintenance_model.php',
    'Pk\\Core\\Database_error' => 'models/support/Database_error.php',
    'Auth_model' => 'models/Auth_model.php',
    'Auth_service' => 'libraries/Auth_service.php',
    'Catalog_model' => 'models/Catalog_model.php',
    'Catalog_service' => 'libraries/Catalog_service.php',
    'Datatable_service' => 'libraries/Datatable_service.php',
    'Document_model' => 'models/Document_model.php',
    'Document_visibility_model' => 'models/Document_visibility_model.php',
    'Document_service' => 'libraries/Document_service.php',
    'Endpoint_registry' => 'libraries/Endpoint_registry.php',
    'File_model' => 'models/File_model.php',
    'File_service' => 'libraries/File_service.php',
    'Http_gateway' => 'libraries/Http_gateway.php',
    'Identity_model' => 'models/Identity_model.php',
    'Pk\\Core\\Context' => 'libraries/support/Context.php',
    'Pk\\Core\\Database' => 'models/support/Database.php',
    'Pk\\Core\\Problem' => 'libraries/support/Problem.php',
    'Pk\\Core\\Rules' => 'libraries/support/Rules.php',
    'Pk\\Core\\Security' => 'libraries/support/Security.php',
    'Pk\\Core\\Seed' => 'libraries/support/Seed.php',
    'Pk\\Core\\UiSchema' => 'libraries/support/UiSchema.php',
    'Pk\\Core\\WorkflowGraph' => 'libraries/support/WorkflowGraph.php',
    'Read_model' => 'models/Read_model.php',
    'Read_service' => 'libraries/Read_service.php',
    'Repository_model' => 'models/Repository_model.php',
    'Request_model' => 'models/Request_model.php',
    'Request_service' => 'libraries/Request_service.php',
    'Transfer_model' => 'models/Transfer_model.php',
    'Transfer_service' => 'libraries/Transfer_service.php',
    'Workflow_model' => 'models/Workflow_model.php',
    'Workflow_service' => 'libraries/Workflow_service.php'
];
